name: Deploy Private GitHub repository to cPanel
on:
  push:
    branches:
      - dev
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.softvencefsd.xyz
          username: mrdawud@mrdawud.softvencefsd.xyz
          password: "0AaGX,4&*p*G"