name: Deploy Private GitHub repository to cPanel
on:
  push:
    branches:
      - dev
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.softvencefsd.xyz
          username: mrdawud@mrdawud.softvencefsd.xyz
          password: "0AaGX,4&*p*G"
